/* The following code was generated by JFlex 1.6.1 */

package br.com.arthurrso.lexicalanalyzer;

import static br.com.arthurrso.lexicalanalyzer.Token.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/arthur.r.oliveira/Documents/UFCG/compiladores/src/main/java/br/com/arthurrso/lexicalanalyzer/language.lex</tt>
 */
public class Lexical {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\5\0\22\0\1\0\1\5\2\0\1\0\1\5\1\3\1\0"+
    "\1\37\1\40\1\7\1\46\1\43\1\44\1\47\1\6\1\1\1\51"+
    "\1\54\1\53\1\55\1\1\1\52\1\1\1\50\1\1\1\5\1\43"+
    "\1\42\1\36\1\45\1\0\1\0\32\2\1\43\1\0\1\43\1\4"+
    "\1\2\1\0\1\13\1\10\1\23\1\15\1\12\1\16\1\26\1\32"+
    "\1\24\1\2\1\14\1\20\1\30\1\22\1\27\1\31\1\2\1\11"+
    "\1\25\1\21\1\17\1\35\1\33\1\56\1\34\1\2\1\43\1\41"+
    "\1\43\1\0\6\0\1\0\32\0\1\0\u15df\0\1\0\u097f\0\13\0"+
    "\35\0\2\0\5\0\1\0\57\0\1\0\u0fa0\0\1\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\2\4\16\2\4\3\1\4"+
    "\1\3\1\4\1\3\1\5\1\4\20\2\1\6\5\2"+
    "\1\6\2\2\2\0\25\2\1\0\1\2\1\7\5\2"+
    "\1\10\13\2\1\1\22\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439"+
    "\0\u0468\0\u0497\0\u04c6\0\u04f5\0\u0524\0\u040a\0\u040a\0\u0553"+
    "\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb"+
    "\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\136"+
    "\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c"+
    "\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04"+
    "\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c"+
    "\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u0df4"+
    "\0\u0e23\0\136\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\136"+
    "\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086"+
    "\0\u10b5\0\u10e4\0\u1113\0\u040a\0\u1142\0\u1171\0\u11a0\0\u11cf"+
    "\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347"+
    "\0\u1376\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\2\5\1\6\1\7\1\10"+
    "\1\11\1\12\2\3\1\13\1\14\1\15\1\3\1\16"+
    "\1\3\1\17\1\20\1\21\1\22\1\3\1\23\1\24"+
    "\3\3\1\25\1\5\1\26\1\27\1\30\1\31\1\27"+
    "\1\32\1\33\1\34\1\35\6\2\1\3\1\0\1\2"+
    "\46\0\6\2\2\0\2\3\5\0\26\3\12\0\7\3"+
    "\3\0\1\27\1\5\31\0\1\27\56\0\1\27\26\0"+
    "\2\36\26\0\1\37\26\0\1\36\27\0\1\37\21\0"+
    "\2\3\5\0\1\3\1\40\22\3\1\41\1\3\12\0"+
    "\7\3\1\0\2\3\5\0\2\3\1\42\1\43\3\3"+
    "\1\44\16\3\12\0\7\3\1\0\2\3\5\0\10\3"+
    "\1\45\15\3\12\0\7\3\1\0\2\3\5\0\2\3"+
    "\1\46\23\3\12\0\7\3\1\0\2\3\5\0\3\3"+
    "\1\47\3\3\1\50\1\51\6\3\1\52\6\3\12\0"+
    "\7\3\1\0\2\3\5\0\14\3\1\53\11\3\12\0"+
    "\7\3\1\0\2\3\5\0\1\3\1\54\22\3\1\55"+
    "\1\3\12\0\7\3\1\0\2\3\5\0\3\3\1\45"+
    "\13\3\1\56\2\3\1\57\3\3\12\0\7\3\1\0"+
    "\2\3\5\0\6\3\1\60\3\3\1\61\5\3\1\62"+
    "\5\3\12\0\7\3\1\0\2\3\5\0\2\3\1\63"+
    "\6\3\1\64\11\3\1\65\2\3\12\0\7\3\1\0"+
    "\2\3\5\0\17\3\1\66\6\3\12\0\7\3\1\0"+
    "\2\3\5\0\3\3\1\67\22\3\12\0\7\3\1\0"+
    "\2\3\5\0\3\3\1\70\22\3\12\0\7\3\1\0"+
    "\2\3\5\0\3\3\1\52\22\3\12\0\7\3\44\0"+
    "\1\71\127\0\1\27\2\0\1\27\53\0\1\27\3\0"+
    "\1\5\1\0\1\27\50\0\1\37\5\0\1\37\50\0"+
    "\1\27\6\0\1\5\47\0\1\37\7\0\1\27\57\0"+
    "\1\72\10\0\2\3\5\0\2\3\1\73\23\3\12\0"+
    "\7\3\1\0\2\3\5\0\11\3\1\74\14\3\12\0"+
    "\7\3\1\0\2\3\5\0\11\3\1\75\14\3\12\0"+
    "\7\3\1\0\2\3\5\0\12\3\1\76\13\3\12\0"+
    "\7\3\1\0\2\3\5\0\12\3\1\74\13\3\12\0"+
    "\7\3\1\0\2\3\5\0\15\3\1\77\10\3\12\0"+
    "\7\3\1\0\2\3\5\0\6\3\1\100\17\3\12\0"+
    "\7\3\1\0\2\3\5\0\10\3\1\101\15\3\12\0"+
    "\7\3\1\0\2\3\5\0\12\3\1\102\13\3\12\0"+
    "\7\3\1\0\2\3\5\0\17\3\1\103\6\3\12\0"+
    "\7\3\1\0\2\3\5\0\1\3\1\60\24\3\12\0"+
    "\7\3\1\0\2\3\5\0\12\3\1\104\13\3\12\0"+
    "\7\3\1\0\2\3\5\0\7\3\1\105\16\3\12\0"+
    "\7\3\1\0\2\3\5\0\21\3\1\77\4\3\12\0"+
    "\7\3\1\0\2\3\5\0\12\3\1\106\5\3\1\107"+
    "\5\3\12\0\7\3\1\0\2\3\5\0\3\3\1\110"+
    "\22\3\12\0\7\3\1\0\2\3\5\0\11\3\1\111"+
    "\14\3\12\0\7\3\1\0\2\3\5\0\21\3\1\112"+
    "\4\3\12\0\7\3\1\0\2\3\5\0\10\3\1\113"+
    "\15\3\12\0\7\3\1\0\2\3\5\0\1\3\1\114"+
    "\24\3\12\0\7\3\1\0\2\3\5\0\14\3\1\115"+
    "\11\3\12\0\7\3\1\0\2\3\5\0\11\3\1\116"+
    "\14\3\12\0\7\3\1\0\2\3\5\0\21\3\1\60"+
    "\4\3\12\0\7\3\1\0\2\3\5\0\13\3\1\117"+
    "\12\3\12\0\7\3\1\0\1\120\46\0\6\120\50\0"+
    "\1\27\10\0\2\3\5\0\3\3\1\121\22\3\12\0"+
    "\7\3\1\0\2\3\5\0\2\3\1\122\23\3\12\0"+
    "\7\3\1\0\2\3\5\0\7\3\1\123\16\3\12\0"+
    "\7\3\1\0\2\3\5\0\16\3\1\77\7\3\12\0"+
    "\7\3\1\0\2\3\5\0\2\3\1\60\23\3\12\0"+
    "\7\3\1\0\2\3\5\0\2\3\1\52\1\124\22\3"+
    "\12\0\7\3\1\0\2\3\5\0\10\3\1\125\4\3"+
    "\1\105\10\3\12\0\7\3\1\0\2\3\5\0\13\3"+
    "\1\60\12\3\12\0\7\3\1\0\2\3\5\0\3\3"+
    "\1\126\22\3\12\0\7\3\1\0\2\3\5\0\11\3"+
    "\1\127\14\3\12\0\7\3\1\0\2\3\5\0\2\3"+
    "\1\130\23\3\12\0\7\3\1\0\2\3\5\0\11\3"+
    "\1\131\3\3\1\132\10\3\12\0\7\3\1\0\2\3"+
    "\5\0\21\3\1\133\4\3\12\0\7\3\1\0\2\3"+
    "\5\0\12\3\1\60\13\3\12\0\7\3\1\0\2\3"+
    "\5\0\2\3\1\134\23\3\12\0\1\122\1\135\1\136"+
    "\1\137\3\3\1\0\2\3\5\0\17\3\1\140\6\3"+
    "\12\0\7\3\1\0\2\3\5\0\2\3\1\141\23\3"+
    "\12\0\7\3\1\0\2\3\5\0\7\3\1\141\16\3"+
    "\12\0\7\3\1\0\2\3\5\0\11\3\1\142\14\3"+
    "\12\0\7\3\1\0\2\3\5\0\17\3\1\60\6\3"+
    "\12\0\7\3\1\0\2\3\5\0\4\3\1\143\21\3"+
    "\12\0\7\3\1\0\1\120\36\0\1\144\7\0\6\120"+
    "\2\0\2\3\5\0\4\3\1\60\21\3\12\0\7\3"+
    "\1\0\2\3\5\0\1\3\1\110\24\3\12\0\7\3"+
    "\1\0\2\3\5\0\7\3\1\145\16\3\12\0\7\3"+
    "\1\0\2\3\5\0\11\3\1\146\14\3\12\0\7\3"+
    "\1\0\2\3\5\0\11\3\1\147\14\3\12\0\7\3"+
    "\1\0\2\3\5\0\26\3\12\0\1\122\1\135\1\136"+
    "\1\137\3\3\1\0\2\3\5\0\14\3\1\150\11\3"+
    "\12\0\7\3\1\0\2\3\5\0\11\3\1\60\14\3"+
    "\12\0\7\3\1\0\2\3\5\0\10\3\1\151\15\3"+
    "\12\0\7\3\1\0\2\3\5\0\1\3\1\152\24\3"+
    "\12\0\7\3\1\0\2\3\5\0\26\3\12\0\2\3"+
    "\1\122\4\3\1\0\2\3\5\0\26\3\12\0\5\3"+
    "\1\122\1\3\1\0\2\3\5\0\26\3\12\0\4\3"+
    "\1\122\2\3\1\0\2\3\5\0\1\3\1\132\24\3"+
    "\12\0\7\3\1\0\2\3\5\0\13\3\1\132\12\3"+
    "\12\0\7\3\1\0\2\3\5\0\13\3\1\153\12\3"+
    "\12\0\7\3\1\0\2\3\5\0\3\3\1\76\22\3"+
    "\12\0\7\3\1\0\2\3\5\0\10\3\1\132\15\3"+
    "\12\0\7\3\1\0\2\3\5\0\22\3\1\154\3\3"+
    "\12\0\7\3\1\0\2\3\5\0\26\3\12\0\2\3"+
    "\1\136\1\137\3\3\1\0\2\3\5\0\12\3\1\155"+
    "\13\3\12\0\7\3\1\0\2\3\5\0\2\3\1\156"+
    "\23\3\12\0\7\3\1\0\2\3\5\0\6\3\1\157"+
    "\17\3\12\0\7\3\1\0\2\3\5\0\22\3\1\60"+
    "\3\3\12\0\7\3\1\0\2\3\5\0\1\3\1\160"+
    "\24\3\12\0\7\3\1\0\2\3\5\0\7\3\1\77"+
    "\16\3\12\0\7\3\1\0\2\3\5\0\26\3\12\0"+
    "\6\3\1\161\1\0\2\3\5\0\3\3\1\162\22\3"+
    "\12\0\7\3\1\0\2\3\5\0\17\3\1\163\6\3"+
    "\12\0\7\3\1\0\2\3\5\0\26\3\12\0\1\3"+
    "\1\164\1\136\4\3\1\0\2\3\5\0\13\3\1\77"+
    "\12\3\12\0\7\3\1\0\2\3\5\0\7\3\1\165"+
    "\16\3\12\0\7\3\1\0\2\3\5\0\26\3\12\0"+
    "\4\3\1\166\2\3\1\0\2\3\5\0\16\3\1\153"+
    "\7\3\12\0\7\3\1\0\2\3\5\0\26\3\12\0"+
    "\1\122\6\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5264];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\25\1\1\11\6\1\2\11\31\1\2\0\25\1"+
    "\1\0\23\1\1\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexical(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 210) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext(); return NUMERO;
            }
          case 9: break;
          case 2: 
            { lexeme=yytext(); return ID;
            }
          case 10: break;
          case 3: 
            { lexeme = yytext(); return OPERADOR;
            }
          case 11: break;
          case 4: 
            { lexeme = yytext(); return OPERADOR_ARIT;
            }
          case 12: break;
          case 5: 
            { lexeme = yytext(); return COMENTARIO;
            }
          case 13: break;
          case 6: 
            { lexeme = yytext(); return PALAVRA;
            }
          case 14: break;
          case 7: 
            { lexeme = yytext(); return NUMBER;
            }
          case 15: break;
          case 8: 
            { lexeme=yytext(); return BOOLEANO;
            }
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
