
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.com.arthurrso.lexicalanalyzer;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SHORT = 45;
  public static final int ANDEQ = 92;
  public static final int IMPLEMENTS = 4;
  public static final int BITNOT = 66;
  public static final int STRICTFP = 32;
  public static final int NOTEQ = 72;
  public static final int PLUSEQ = 88;
  public static final int RBRACK = 58;
  public static final int CATCH = 19;
  public static final int COMMA = 60;
  public static final int RBRACE = 56;
  public static final int THROW = 21;
  public static final int RPAREN = 54;
  public static final int LBRACK = 57;
  public static final int ANDAND = 73;
  public static final int OROR = 74;
  public static final int DOUBLE = 49;
  public static final int LBRACE = 55;
  public static final int TRANSIENT = 29;
  public static final int LPAREN = 53;
  public static final int XOREQ = 94;
  public static final int PROTECTED = 34;
  public static final int INTEGER_LITERAL = 42;
  public static final int FALSE = 52;
  public static final int NOT = 65;
  public static final int FINAL = 26;
  public static final int FLOAT = 47;
  public static final int PACKAGE = 23;
  public static final int MOD = 84;
  public static final int CLASS = 2;
  public static final int SUPER = 31;
  public static final int ABSTRACT = 25;
  public static final int TRUE = 51;
  public static final int NATIVE = 27;
  public static final int PLUS = 77;
  public static final int LONG = 48;
  public static final int QUESTION = 67;
  public static final int WHILE = 17;
  public static final int EQUAL = 62;
  public static final int EXTENDS = 3;
  public static final int INTERFACE = 5;
  public static final int CHAR = 44;
  public static final int BOOLEAN = 41;
  public static final int SWITCH = 16;
  public static final int DO = 11;
  public static final int FOR = 14;
  public static final int RSHIFTEQ = 97;
  public static final int GREATER = 63;
  public static final int DIV = 80;
  public static final int VOID = 37;
  public static final int MULT = 79;
  public static final int PUBLIC = 33;
  public static final int RETURN = 15;
  public static final int ELSE = 13;
  public static final int TRY = 18;
  public static final int GTEQ = 71;
  public static final int BREAK = 7;
  public static final int DOT = 61;
  public static final int INT = 46;
  public static final int STRING_LITERAL = 99;
  public static final int NULL = 38;
  public static final int EQEQ = 69;
  public static final int EOF = 0;
  public static final int SEMICOLON = 59;
  public static final int THIS = 39;
  public static final int DEFAULT = 10;
  public static final int MULTEQ = 90;
  public static final int IMPORT = 22;
  public static final int MINUS = 78;
  public static final int FLOAT_LITERAL = 43;
  public static final int LTEQ = 70;
  public static final int OR = 82;
  public static final int URSHIFT = 87;
  public static final int error = 1;
  public static final int SYNCHRONIZED = 28;
  public static final int DIVEQ = 91;
  public static final int LSHIFTEQ = 96;
  public static final int FINALLY = 20;
  public static final int CONTINUE = 9;
  public static final int IF = 12;
  public static final int INSTANCEOF = 40;
  public static final int ID = 98;
  public static final int MODEQ = 95;
  public static final int MINUSMINUS = 76;
  public static final int COLON = 68;
  public static final int OREQ = 93;
  public static final int VOLATILE = 30;
  public static final int PLUSPLUS = 75;
  public static final int CASE = 8;
  public static final int NEW = 6;
  public static final int RSHIFT = 86;
  public static final int STRING = 50;
  public static final int LESS = 64;
  public static final int BYTE = 24;
  public static final int AND = 81;
  public static final int PRIVATE = 35;
  public static final int STATIC = 36;
  public static final int LSHIFT = 85;
  public static final int XOR = 83;
  public static final int MINUSEQ = 89;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "EXTENDS",
  "IMPLEMENTS",
  "INTERFACE",
  "NEW",
  "BREAK",
  "CASE",
  "CONTINUE",
  "DEFAULT",
  "DO",
  "IF",
  "ELSE",
  "FOR",
  "RETURN",
  "SWITCH",
  "WHILE",
  "TRY",
  "CATCH",
  "FINALLY",
  "THROW",
  "IMPORT",
  "PACKAGE",
  "BYTE",
  "ABSTRACT",
  "FINAL",
  "NATIVE",
  "SYNCHRONIZED",
  "TRANSIENT",
  "VOLATILE",
  "SUPER",
  "STRICTFP",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "VOID",
  "NULL",
  "THIS",
  "INSTANCEOF",
  "BOOLEAN",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "CHAR",
  "SHORT",
  "INT",
  "FLOAT",
  "LONG",
  "DOUBLE",
  "STRING",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "EQUAL",
  "GREATER",
  "LESS",
  "NOT",
  "BITNOT",
  "QUESTION",
  "COLON",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "AND",
  "OR",
  "XOR",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "ANDEQ",
  "OREQ",
  "XOREQ",
  "MODEQ",
  "LSHIFTEQ",
  "RSHIFTEQ",
  "ID",
  "STRING_LITERAL"
  };
}

