
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.com.arthurrso.lexicalanalyzer;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ANDEQ = 59;
  public static final int TYPE = 80;
  public static final int GO = 71;
  public static final int CONST = 85;
  public static final int NOTEQ = 39;
  public static final int PLUSEQ = 55;
  public static final int FUNC = 81;
  public static final int ASSIGNMENT = 66;
  public static final int DEFER = 86;
  public static final int RBRACK = 27;
  public static final int COMMA = 29;
  public static final int RBRACE = 25;
  public static final int ANDNOTEQ = 74;
  public static final int RECIEVER = 72;
  public static final int RPAREN = 23;
  public static final int LBRACK = 26;
  public static final int ANDAND = 40;
  public static final int OROR = 41;
  public static final int INTEGER = 21;
  public static final int STRUCT = 88;
  public static final int LBRACE = 24;
  public static final int LPAREN = 22;
  public static final int XOREQ = 61;
  public static final int FALSE = 20;
  public static final int NOT = 34;
  public static final int ERROR = 84;
  public static final int VAR = 76;
  public static final int GOTO = 82;
  public static final int PACKAGE = 14;
  public static final int MOD = 51;
  public static final int SELECT = 87;
  public static final int FALLTHROUGH = 89;
  public static final int RUNE = 78;
  public static final int TRUE = 19;
  public static final int PLUS = 44;
  public static final int EQUAL = 31;
  public static final int INTERFACE = 2;
  public static final int BOOLEAN = 16;
  public static final int CHAN = 79;
  public static final int SWITCH = 12;
  public static final int VARIABLE = 65;
  public static final int FOR = 10;
  public static final int RSHIFTEQ = 64;
  public static final int GREATER = 32;
  public static final int DIV = 47;
  public static final int RETURN = 11;
  public static final int MULT = 46;
  public static final int ANDNOT = 68;
  public static final int ELSE = 9;
  public static final int BREAK = 4;
  public static final int GTEQ = 38;
  public static final int DOT = 30;
  public static final int INT = 17;
  public static final int MAP = 75;
  public static final int STRING_LITERAL = 90;
  public static final int EQEQ = 36;
  public static final int EOF = 0;
  public static final int SEMICOLON = 28;
  public static final int DEFAULT = 7;
  public static final int FUNCTION = 67;
  public static final int FUNCTION_PARAMS = 69;
  public static final int MULTEQ = 57;
  public static final int CALL_FUNCTION = 70;
  public static final int IMPORT = 13;
  public static final int MINUS = 45;
  public static final int LTEQ = 37;
  public static final int OR = 49;
  public static final int error = 1;
  public static final int URSHIFT = 54;
  public static final int DIVEQ = 58;
  public static final int LSHIFTEQ = 63;
  public static final int CONTINUE = 6;
  public static final int SHORTDECLARATION = 73;
  public static final int IF = 8;
  public static final int MODEQ = 62;
  public static final int MINUSMINUS = 43;
  public static final int COLON = 35;
  public static final int OREQ = 60;
  public static final int CASE = 5;
  public static final int PLUSPLUS = 42;
  public static final int NEW = 3;
  public static final int RANGE = 83;
  public static final int RSHIFT = 53;
  public static final int STRING = 18;
  public static final int LESS = 33;
  public static final int BYTE = 15;
  public static final int AND = 48;
  public static final int ELLIPSIS = 77;
  public static final int LSHIFT = 52;
  public static final int XOR = 50;
  public static final int MINUSEQ = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTERFACE",
  "NEW",
  "BREAK",
  "CASE",
  "CONTINUE",
  "DEFAULT",
  "IF",
  "ELSE",
  "FOR",
  "RETURN",
  "SWITCH",
  "IMPORT",
  "PACKAGE",
  "BYTE",
  "BOOLEAN",
  "INT",
  "STRING",
  "TRUE",
  "FALSE",
  "INTEGER",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "EQUAL",
  "GREATER",
  "LESS",
  "NOT",
  "COLON",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "AND",
  "OR",
  "XOR",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "ANDEQ",
  "OREQ",
  "XOREQ",
  "MODEQ",
  "LSHIFTEQ",
  "RSHIFTEQ",
  "VARIABLE",
  "ASSIGNMENT",
  "FUNCTION",
  "ANDNOT",
  "FUNCTION_PARAMS",
  "CALL_FUNCTION",
  "GO",
  "RECIEVER",
  "SHORTDECLARATION",
  "ANDNOTEQ",
  "MAP",
  "VAR",
  "ELLIPSIS",
  "RUNE",
  "CHAN",
  "TYPE",
  "FUNC",
  "GOTO",
  "RANGE",
  "ERROR",
  "CONST",
  "DEFER",
  "SELECT",
  "STRUCT",
  "FALLTHROUGH",
  "STRING_LITERAL"
  };
}

